// packages/react/hooks/use-focus-trap/src/use-focus-trap.ts
import { useEffect, useRef } from 'react'
import type { RefObject } from 'react'
import { trapFocus } from '@dunky.dev/dom-focus-trap'
import type { TrapFocusOptions } from '@dunky.dev/dom-focus-trap'

export interface UseFocusTrapOptions extends TrapFocusOptions {}

/**
 * Traps Tab / Shift+Tab within `target` while mounted — the React lifecycle
 * around `trapFocus`. Call it from the component that renders the container,
 * so both mount together: the trap binds once, when the target first exists.
 */
export function useFocusTrap(
  target: RefObject<HTMLElement | null>,
  options: UseFocusTrapOptions = {},
): void {
  // Read through a ref so inline option closures don't re-bind the listener
  // on every render.
  const optionsRef = useRef(options)
  optionsRef.current = options

  useEffect(() => {
    const container = target.current
    if (container === null) return
    return trapFocus(container, {
      enabled: () => optionsRef.current.enabled?.() !== false,
      last: () => optionsRef.current.last?.() ?? null,
    })
  }, [target])
}

// packages/solid/hooks/use-focus-trap/src/use-focus-trap.ts
import { createEffect, untrack } from 'solid-js'
import { trapFocus } from '@dunky.dev/dom-focus-trap'
import type { TrapFocusOptions } from '@dunky.dev/dom-focus-trap'

export interface UseFocusTrapOptions extends TrapFocusOptions {}

/**
 * Traps Tab / Shift+Tab within `target` while it holds an element — the Solid
 * lifecycle around `trapFocus`. Arms when the target yields an element,
 * releases on dispose, re-arms when a reactive accessor yields a new one.
 */
export function useFocusTrap(
  target: () => HTMLElement | null | undefined,
  options: UseFocusTrapOptions = {},
): void {
  // The compute tracks a reactive target; the apply re-reads it fresh —
  // compute runs eagerly at creation, before a plain ref variable fills.
  // Options are read per Tab press, so inline `enabled` / `last` stay live
  // without re-binding the listener.
  createEffect(
    () => target(),
    () => {
      const container = untrack(target)
      if (container == null) return
      return trapFocus(container, {
        enabled: () => options.enabled?.() !== false,
        last: () => options.last?.() ?? null,
      })
    },
  )
}
